Name : Drona Jaybhaye

Branch: Computer

Topic:Numpy Functions

In [1]:
import numpy as drona
a = drona.array(['cherry','apple','mango'])
print(a)  

['cherry' 'apple' 'mango']


In [2]:
z = drona.zeros((1,2))
print(z)

[[0. 0.]]


In [3]:
o = drona.ones((10, 10))
print(o)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [4]:
i = drona.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
r = drona.arange(0, 10, 2)
print(r)  

[0 2 4 6 8]


In [6]:
a = drona.array([1, 2, 3, 4, 5, 6])
reshaped = a.reshape((2, 3))
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [7]:
a = drona.array([1, 2])
b = drona.array([3, 4])
combined = drona.concatenate((a, b))
print(combined)  

[1 2 3 4]


In [8]:
a = drona.array([1, 2, 3, 4])
print(drona.mean(a)) 

2.5


In [10]:
a = drona.array([[1, 2], [3, 4]])
print(drona.sum(a))  

10


In [11]:
arr = drona.array([4, 7, 1, 9])
print(drona.max(arr))


9


In [12]:
arr = drona.array([4, 7, 1, 9])
print(drona.min(arr))


1


In [13]:
arr = drona.array([1, 2, 2, 3, 3, 3])
unique_vals = drona.unique(arr)
print(unique_vals)


[1 2 3]


In [15]:
arr = drona.array([10, 21, 30])
print(drona.std(arr))


8.178562764256865


In [16]:
a = drona.array([1, 2])
b = drona.array([3, 4])
print(drona.dot(a, b))  


11
